server:
  port: 8100
endpoints:
  health:
    sensitive: false
  shutdown:
    enabled: true
spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://dockerhost:3306/demo
    username: root
    password: p@ssw0rd
    driver-class-name: com.mysql.jdbc.Driver

  server:
    port: ${PORT:8100}

  name: World